version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: python -m pip install --user -r requirements/dev.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
